# -*- coding: utf-8 -*-
"""firstaidchatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-D3d0zLjjRmbrs_W10BjNiJQXnQZ4Ay
"""

!pip install -q groq gradio

import os
from groq import Groq
import gradio as gr

# Initialize Groq client
# You'll need to set your API key
GROQ_API_KEY = ""  # Replace with your actual API key
client = Groq(api_key=GROQ_API_KEY)

def is_first_aid_related(user_message, client):
    """Check if the user's question is related to first aid"""
    system_prompt = """You are a classifier that determines if a question is related to first aid, medical emergencies, injuries, or health emergencies.

    Respond with ONLY 'YES' if the question is about:
    - First aid procedures
    - Medical emergencies
    - Injuries and their treatment
    - CPR, wound care, burns, fractures, choking, etc.
    - Emergency health situations

    Respond with ONLY 'NO' if the question is about anything else.

    Output only YES or NO, nothing else."""

    try:
        response = client.chat.completions.create(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message}
            ],
            model="llama-3.3-70b-versatile",
            temperature=0.1,
            max_tokens=10
        )

        result = response.choices[0].message.content.strip().upper()
        return "YES" in result
    except Exception as e:
        print(f"Classification error: {e}")
        return False

def first_aid_assistant(user_message, history):
    """Main chatbot function"""

    # Check if question is first aid related
    if not is_first_aid_related(user_message, client):
        return "I'm sorry, but I can only assist with first aid and medical emergency questions. Please ask me about injuries, emergency procedures, CPR, wound care, or other first aid topics."

    # If it's first aid related, get the response
    system_prompt = """You are a knowledgeable First Aid Assistant. Your role is to provide clear, accurate, and helpful first aid guidance for medical emergencies and injuries.

Guidelines:
- Provide step-by-step first aid instructions
- Be clear and concise
- Emphasize when to seek professional medical help
- Always prioritize safety
- Use simple language that anyone can understand
- Include important warnings when necessary

Remember: You provide first aid guidance, but always advise seeking professional medical help for serious conditions."""

    try:
        # Build conversation history
        messages = [{"role": "system", "content": system_prompt}]

        # Add conversation history
        for human, assistant in history:
            messages.append({"role": "user", "content": human})
            messages.append({"role": "assistant", "content": assistant})

        # Add current message
        messages.append({"role": "user", "content": user_message})

        # Get response from Groq
        response = client.chat.completions.create(
            messages=messages,
            model="llama-3.3-70b-versatile",
            temperature=0.7,
            max_tokens=1024
        )

        return response.choices[0].message.content

    except Exception as e:
        return f"An error occurred: {str(e)}\n\nPlease check your API key and try again."

# Create Gradio interface
with gr.Blocks(title="First Aid Assistant", theme=gr.themes.Soft()) as demo:
    gr.Markdown(
        """
        # 🏥 First Aid Assistant

        Ask me anything about first aid, medical emergencies, injuries, or emergency procedures.
        I'm here to help with guidance on CPR, wound care, burns, fractures, and more!

        **⚠️ Disclaimer:** This is for informational purposes only. Always seek professional medical help in emergencies.
        """
    )

    chatbot = gr.Chatbot(
        height=500,
        label="First Aid Chat",
        avatar_images=(None, "🏥")
    )

    with gr.Row():
        msg = gr.Textbox(
            label="Your Question",
            placeholder="E.g., How do I treat a minor burn?",
            scale=4
        )
        submit = gr.Button("Send", scale=1, variant="primary")

    with gr.Row():
        clear = gr.Button("Clear Chat")

    gr.Markdown(
        """
        ### Example Questions:
        - How do I perform CPR?
        - What should I do for a severe cut?
        - How to treat a bee sting?
        - What are the signs of a heart attack?
        """
    )

    def respond(message, chat_history):
        bot_message = first_aid_assistant(message, chat_history)
        chat_history.append((message, bot_message))
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])
    submit.click(respond, [msg, chatbot], [msg, chatbot])
    clear.click(lambda: None, None, chatbot, queue=False)

# Launch the app
if __name__ == "__main__":
    print("🏥 Starting First Aid Assistant...")
    print("⚠️  Remember to replace 'your_groq_api_key_here' with your actual Groq API key!")
    demo.launch(debug=True)